### ISSUE TITLE
READMEの記述ミス

### ISSUE THREAD

**Issue by ray45422** [taka-tuos/nanotter#1]
ビルド方法の項に`$ cd nanotter/twitcurl`とあるがtwicurlは存在していない
`$ cd nanotter/libtwicurl`では無いだろうか
もしくはディレクトリ名のミスだと思うのでどちらかの方法で修正すると良いかと思います

あとバイナリファイルはgitで管理するには不向きなので.gitignoreに追加するといいと思います

**Comment by taka-tuos** [comment]
修正しました。
指摘ありがとうございました。
